DROP DATABASE IF EXISTS SINAU;
CREATE DATABASE SINAU;
USE SINAU;



CREATE TABLE ENDERECO(
    IDENDERECO INTEGER NOT NULL AUTO_INCREMENT,
    RUA VARCHAR(40),
    NUMERO INTEGER,
    BAIRRO VARCHAR(40),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(2),
    CEP INTEGER(9),
    PRIMARY KEY (IDENDERECO)
)Engine=InnoDB;



CREATE TABLE INSTITUTO(
    IDINSTITUTO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    IDENDERECO INTEGER NOT NULL,
    PRIMARY KEY (IDINSTITUTO),
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO) ON DELETE CASCADE
)Engine=InnoDB;



CREATE TABLE DEPARTAMENTO(
    IDDEPARTAMENTO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    TELEFONE INTEGER(9),
    IDINSTITUTO INTEGER,
    PRIMARY KEY (IDDEPARTAMENTO),
    FOREIGN KEY (IDINSTITUTO) REFERENCES INSTITUTO(IDINSTITUTO) ON DELETE CASCADE
)Engine=InnoDB;



CREATE TABLE CURSO(
    IDCURSO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    AREA VARCHAR(40),
    VAGAS INTEGER,
    IDDEPARTAMENTO INTEGER,
    PRIMARY KEY (IDCURSO),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO) ON DELETE CASCADE
)Engine=InnoDB;

CREATE TABLE PROFESSOR(
    IDPROFESSOR INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    EMAIL VARCHAR(60),
    IDENDERECO INTEGER,
    TELEFONE INTEGER(9),
    COORDENADOR tinyint(1),
    IDDEPARTAMENTO INTEGER,
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    ADMINISTRADOR tinyint(1),
    PRIMARY KEY (IDPROFESSOR),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO) ON DELETE CASCADE
)Engine=InnoDB;

CREATE TABLE DISCIPLINA(
    IDDISCIPLINA INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    DESCRICAO VARCHAR(400),
    CARGAHORARIA INTEGER,
    IDCURSO INTEGER,
    HORARIO DATETIME,
    SALA INTEGER,
    IDPROFESSOR INTEGER,
    PRIMARY KEY (IDDISCIPLINA),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO) ON DELETE CASCADE,
    FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR) ON DELETE CASCADE
)Engine=InnoDB;


CREATE TABLE ALUNO(
    IDALUNO INTEGER NOT NULL AUTO_INCREMENT,
    MATRICULA VARCHAR(15),
    NOME VARCHAR(40),
    EMAIL VARCHAR(60),
    IDENDERECO INTEGER,
    TELEFONE INTEGER(9),
    BOLSISTA tinyint(1),
    ANOINICIO INTEGER,
    IDCURSO INTEGER,
    SEMESTRE tinyint(2),
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    PRIMARY KEY (IDALUNO),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO) ON DELETE CASCADE
)Engine=InnoDB;


CREATE TABLE CURSA_DISCIPLINA(
IDALUNO INTEGER NOT NULL,
IDDISCIPLINA INTEGER NOT NULL,
PROVA_1 DECIMAL(10,2),
PROVA_2 DECIMAL(10,2),
TABALHO DECIMAL(10,2),
LISTA DECIMAL(10,2),
PRIMARY KEY (IDDISCIPLINA,IDALUNO),
FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO) ON DELETE CASCADE,
FOREIGN KEY (IDDISCIPLINA) REFERENCES DISCIPLINA(IDDISCIPLINA) ON DELETE CASCADE
)Engine=InnoDB;