CREATE DATABASE SINAU;
USE SINAU;



CREATE TABLE ENDERECO(
    IDENDERECO INTEGER NOT NULL AUTO_INCREMENT,
    RUA VARCHAR(40),
    NUMERO INTEGER,
    BAIRRO VARCHAR(40),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(2),
    CEP INTEGER(9),
    PRIMARY KEY (IDENDERECO)
);



CREATE TABLE INSTITUTO(
    IDINSTITUTO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    IDENDERECO INTEGER NOT NULL,
    PRIMARY KEY (IDINSTITUTO),
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO)
);



CREATE TABLE DEPARTAMENTO(
    IDDEPARTAMENTO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    TELEFONE INTEGER(9),
    IDINSTITUTO INTEGER,
    PRIMARY KEY (IDDEPARTAMENTO),
    FOREIGN KEY (IDINSTITUTO) REFERENCES INSTITUTO(IDINSTITUTO)
);



CREATE TABLE CURSO(
    IDCURSO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    AREA VARCHAR(40),
    VAGAS INTEGER,
    IDDEPARTAMENTO INTEGER,
    PRIMARY KEY (IDCURSO),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);

CREATE TABLE PROFESSOR(
    IDPROFESSOR INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    EMAIL VARCHAR(60),
    IDENDERECO INTEGER,
    TELEFONE INTEGER(9),
    COORDENADOR BIT,
    IDDEPARTAMENTO INTEGER,
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    ADMINISTRADOR BIT,
    PRIMARY KEY (IDPROFESSOR),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);

CREATE TABLE DISCIPLINA(
    IDDISCIPLINA INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40),
    DESCRICAO VARCHAR(400),
    CARGAHORARIA INTEGER,
    IDCURSO INTEGER,
    HORARIO DATETIME,
    SALA INTEGER,
    IDPROFESSOR INTEGER,
    PRIMARY KEY (IDDISCIPLINA),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO),
    FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR)
);


CREATE TABLE ALUNO(
    IDALUNO INTEGER NOT NULL AUTO_INCREMENT,
    MATRICULA VARCHAR(15),
    NOME VARCHAR(40),
    EMAIL VARCHAR(60),
    IDENDERECO INTEGER,
    TELEFONE INTEGER(9),
    BOLSISTA BIT,
    ANOINICIO INTEGER,
    IDCURSO INTEGER,
    SEMESTRE BIT,
    USUARIO VARCHAR(40),
    SENHA VARCHAR(40),
    PRIMARY KEY (IDPROFESSOR),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO)
);